server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: sec
    password: sec1234
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 332362076982-96bp9gj2o51hvkp34s52g80mvidg2i12.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
