server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: sec
    password: sec1234
    
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 332362076982-96bp9gj2o51hvkp34s52g80mvidg2i12.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 678904487163123
            client-secret: 22689eef69204fcbc37254b6b4c1f0c7
            scope:
            - email
            - public_profile
            
          naver:
            client-id: H7iQ8lacaqvLoulmLrn4
            client-secret: PyblN1DI4p
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response     # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
